<?php
	global $wpdb, $msg, $msgt;
	
	//get/set settings
	global $pmpro_pages;
	if($_REQUEST['savesettings'])
	{                   		
		//email options
		pmpro_setOption("from_email");
		pmpro_setOption("from_name");

		//assume success
		$msg = true;
		$msgt = "Your email settings have been updated.";		
	}
	
	$from_email = pmpro_getOption("from_email");
	$from_name = pmpro_getOption("from_name");
	
	if(!$from_email)
	{
		$parsed = parse_url(home_url()); 
		$hostname = $parsed[host];
		$hostparts = split("\.", $hostname);				
		$email_domain = $hostparts[count($hostparts) - 2] . "." . $hostparts[count($hostparts) - 1];		
		$from_email = "wordpress@" . $email_domain;
		pmpro_setOption("from_email", $from_email);
	}
	
	if(!$from_name)
	{		
		$from_name = "WordPress";
		pmpro_setOption("from_name", $from_name);
	}
				
	require_once(dirname(__FILE__) . "/admin_header.php");		
?>

	<form action="" method="post" enctype="multipart/form-data"> 
		<h2>Email Settings</h2>
		<p>By default, system generated emails are sent from <em><strong>wordpress@yourdomain.com</strong></em>. You can update this from address using the fields below.</p>
		
		<p>To modify the appearance of system generated emails, add the files <em>email_header.html</em> and <em>email_footer.html</em> to your theme's directory. This will modify both the WordPress default messages as well as messages generated by Paid Memberships Pro. <a title="Paid Memberships Pro - Member Communications" target="_blank" href="http://www.paidmembershipspro.com/support/member-communications/">Click here to learn more about Paid Memberships Pro emails</a>.</p>
					
		<table class="form-table">
		<tbody>                
			<tr>
				<th scope="row" valign="top">
					<label for="from_email">From Email:</label>
				</th>
				<td>
					<input type="text" name="from_email" size="60" value="<?php echo $from_email?>" />
				</td>
			</tr>
			<tr>
				<th scope="row" valign="top">
					<label for="from_name">From Name:</label>
				</th>
				<td>
					<input type="text" name="from_name" size="60" value="<?php echo $from_name?>" />
				</td>
			</tr>
		</tbody>
		</table>
		<p class="submit">            
			<input name="savesettings" type="submit" class="button-primary" value="Save Settings" /> 		                			
		</p> 
	</form>

<?php
	require_once(dirname(__FILE__) . "/admin_footer.php");	
?>
